### ISSUE TITLE
Please add the 'thinkscript' file extension "tosts"

### ISSUE THREAD

**Issue by madburg** [RiderTradingTools/thinkscript#1]
Please add the official 'thinkscript' file extension of "tosts" in the package configuration json file:

https://github.com/RiderTradingTools/thinkscript/blob/46d31153b185aa64c17a9103e201363bd13de53a/package.json#L24

`				"extensions": [
					".thinkscript",
					".tosts"
				],`

Leaving the non-official .thinkscript extension is fine

**Comment by RiderTradingTools** [comment]
Good idea.  I will also add ".ts" since that file extension is documented on toslc.thinkorswim.com:

[https://toslc.thinkorswim.com/center/howToTos/thinkManual/charts/Using-Studies-and-Strategies](https://toslc.thinkorswim.com/center/howToTos/thinkManual/charts/Using-Studies-and-Strategies)

**Comment by RiderTradingTools** [comment]
Included .tosts file extension in v1.0.2
